[build]
  functions = "functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

# ✅ Rút gọn URL: /home, /gpt/... , /gemini/... đều hoạt động
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
